ai:
  kimi:
    api-key: ${KIMI_API_KEY}
    base-url: https://api.moonshot.cn
    model: moonshot-v1-8k

  qwen:
    api-key: ${ALI_API_KEY}
    base-url: https://dashscope.aliyuncs.com/compatible-mode
    model: qwen-plus
    embedding-model: text-embedding-v3

spring:
  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
      embedding:
        model: deepseek-embed